### PR TITLE
Doc: reworked CMSIS-RTOS2 for better abstraction from RTX and cleaned out errors.

### PR DESCRIPTION
**Pull request by vovamarch**

### CODE REVIEW

**Review by JonatanAntoni — DISMISSED** [review]

**Comment by KeilChris** [comment]
Why have you dropped the migration from v1 to v2? Do you think this is not necessary anymore?
Also, I'm missing the small text explaining the common design concepts (formerly in the Function Overview section). Should we add that in the "Using" section?

**Comment by vovamarch** [comment]
> Why have you dropped the migration from v1 to v2? Do you think this is not necessary anymore?

I  think we don't need to have the migration from API v1 as prominent, especially as this part may also need maintenance for new changes in API v2, also CMSIS-RTX doesn't support API v1. But having a reference that info for such migration is available in the CMSIS 5 doc can be useful. I'll  see where that could best fit.

>  Also, I'm missing the small text explaining the common design concepts (formerly in the Function Overview section). Should we add that in the "Using" section?

The text in "Common Design Concepts" is now available in "Lifecycle of RTOS Objects". I renamed it, so that it better reflects what the content, and can be good aligned with System Startup section before it. One thing that got lost is a paragraph with coding rules, I'll add that.

**Comment by ReinhardKeil** [comment]
> Why have you dropped the migration from v1 to v2? Do you think this is not necessary anymore? Also, I'm missing the small text explaining the common design concepts (formerly in the Function Overview section). Should we add that in the "Using" section?

I would refer to CMSIS_5 documentation for this.  By now (after ~5 years) most users have migrated already.

**Review by KeilChris — APPROVED** [review]
LGTM

**Review by RobertRostohar — COMMENTED** [review]
Looks good to me.

**Pull request merged**
