### PR TITLE
Added Virtual Timer support

### PR DESCRIPTION
**Pull request by Mayankbht**
Updated cmsis_cp15.h and core_ca.h files for adding Virtual Timer Support in CMSIS_6 for Cortex A7.

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
@Mayankbht, sorry for the delay. May I ask you to
- update the PR with latest clean ups, and
- check CoreValidation test suite. Is it feasible to add test cases for the new features?
- Additionally, check PR #52 if this new test approach could be helpful as well.

**Comment by JonatanAntoni** [comment]
@Mayankbht,

Are you still working on this contribution?

**Comment by Mayankbht** [comment]
Hi @JonatanAntoni, I am quite not sure if I have enough knowledge about adding tests in  CoreValidation test suite. Can anyone at your end test this using the test suite suggested please?

**Comment by JonatanAntoni** [comment]
> I am quite not sure if I have enough knowledge about adding tests in CoreValidation test suite. Can anyone at your end test this using the test suite suggested please?

Might be good if you could have a look at the tests least. The Core tests don't need any specific commercial tools and should run on your system. The CoreValidation tests need ARM Fast Models to be executed. This might be a hurdle for you depending on your tool env.

Could you please at least rebase the PR so that we can get it merged? Its just an addition of new functions so I am confident it doesn't break any existing functionality. Not sure how a test case could look like without knowing more details.

**Comment by Mayankbht** [comment]
Sure I will rebase.

**Comment by Mayankbht** [comment]
Since the folder structure is completely changed now, I will create another PR for the rebased patch.

**Comment by Mayankbht** [comment]
New PR after rebasing is created: https://github.com/ARM-software/CMSIS_6/pull/127
@JonatanAntoni, please merge it soon to avoid further rebasing.

**Pull request closed without merging**
