### PR TITLE
Enhance the cast from uint32_t to uint32_t* by intermediate casting through uintptr_t in __NVIC_SetVector/GetVector

### PR DESCRIPTION
**Pull request by M-Bab**
This allows the header to be compiled on a non-32bit architecture without the warning int-to-pointer-cast. It is also a clean approach when turning a uint32_t value to a pointer and should not add any additional cycles on a 32bit architecture.

The next obvious question would be: Why should I ever compile these very specific headers on a different architecture?

The answer: For example for _unit testing the embedded code on an x64 host_. When trying to do this, these files alone emits dozens of warnings:

```
... Include/core_cm0plus.h: In function ‘__NVIC_SetVector’:
... Include/core_cm0plus.h:890:23: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  890 |   uint32_t *vectors = (uint32_t *) ((uint32_t) SCB->VTOR);
      |                       ^
... Include/core_cm0plus.h: In function ‘__NVIC_GetVector’:
... Include/core_cm0plus.h:909:23: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  909 |   uint32_t *vectors = (uint32_t *) ((uint32_t) SCB->VTOR);
```

Depending on the Werror policy during unit-testing it might stop your efforts immediately.

This is the MR https://github.com/ARM-software/CMSIS_5/pull/1633 re-applied on CMSIS v6.

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Looks basically fine for me. But instead of another cast, could we think about changing the declaration of `SCB_Type`? `VTOR` is currently declared `uint32_t`. We might just change this to `uintptr_t`.

Another option might be to introduce an unnamed union to overlay the address with the pointer representation, getting rid of the casts completely. Unfortunately, such an overlay would violate the strict aliasing rule.

**Comment by M-Bab** [comment]
> Looks basically fine for me. But instead of another cast, could we think about changing the declaration of `SCB_Type`? `VTOR` is currently declared `uint32_t`. We might just change this to `uintptr_t`.

I would consider my MR to be minimal invasive because it is not effectively changing anything. Changing the VTOR type to uintptr_t also sounds reasonable because it is the nature of VTOR. However, it may change the size of SCB_Type for different architectures.

I like to look at it in the following way: This MR is a minimal invasive way to get corner cases like unit tests on a different architecture working without hassle.
Changing VTOR to uintptr_t is more like "how could it work, if we have 64bit Cortex M processors in the future?"

> Another option might be to introduce an unnamed union to overlay the address with the pointer representation, getting rid of the casts completely. Unfortunately, such an overlay would violate the strict aliasing rule.

I would rather not do that.

**Comment by JonatanAntoni** [comment]
> Changing the VTOR type to uintptr_t also sounds reasonable because it is the nature of VTOR. However, it may change the size of SCB_Type for different architectures.

Good point. In `SCB_Type` we need to fix this to 32bit. This would break the layout when compiling for any 64bit host machine. So, probably the MR using casts is the way we should fix this.

**Review by GuentherMartin — APPROVED** [review]
Changes look fine to me.

**Pull request merged**
