### PR TITLE
Resolve gcc undef warnings

### PR DESCRIPTION
**Pull request by holden-zenith**

### CODE REVIEW

**Review by JonatanAntoni — DISMISSED** [review]

**Comment by GuentherMartin** [comment]
Hello @holden-zenith, Hello @JonatanAntoni ,
I would suggest to apply these changes to all compiler header file.
Why is the `#if defined` guard only used in checks like
 `#if defined (__ARM_FEATURE_CMSE) && (__ARM_FEATURE_CMSE == 3) `
and not in checks like
`#if (((__ARM_ARCH_8M_MAIN__   < 1) && \
      (__ARM_ARCH_8_1M_MAIN__ < 1)    ) && \
	 (__ARM_FEATURE_CMSE < 3)              )
`
This looks inconsistent me. Shouldn't the 2nd check not also throw a warning?

**Comment by holden-zenith** [comment]
@GuentherMartin I don't mind adding the def guard to the other compilers, but if they silently default to 0 then there's not much value in doing so. And I will add those other checks, I missed them.

**Comment by GuentherMartin** [comment]
@holden-zenith, I don't mind if the def guard silently defaults to 0 for other compilers but it makes life easier when you compare the header files.

**Comment by JonatanAntoni** [comment]
> Should the iccarm one have the **ARM_ARCH_8_1M_MAIN** check as well?

Not sure about IARARM. Compilers are not consistent about these macros. I'd leave the macros as are.

> Also, out of curiosity why is the iccarm compiler file so differently formatted than the others?


The cmsis_iar.h was provided by IAR.

**Comment by ReinhardKeil** [comment]
I did ask IAR to provide an answer on `cmsis_iar.h`

**Comment by bastkerg** [comment]
> I did ask IAR to provide an answer on `cmsis_iar.h`

I'm looking into this.

**Comment by RobinKastberg** [comment]
So my first reaction is that everywhere we check for v8 we should check for v8 or v8.1. Is that correct?

Also should I `define __ARM_ARCH_8_1M_MAIN__`? It is not referred to in [documentation](https://arm-software.github.io/CMSIS_6/latest/Core/group__compiler__conntrol__gr.html)

While investigating I read the following [comment](https://github.com/ARM-software/CMSIS_5/issues/1210#issuecomment-1661733215)

> Using arch defines like __ARM_ARCH_8_1M_MAIN__ is discouraged. Instead we got advised to use __ARM_ARCH and __ARM_ARCH_ISA_THUMB instead. This has already been applied for LLVM/Clang in https://github.com/ARM-software/CMSIS_6/blob/main/CMSIS/Core/Include/cmsis_clang.h. A similar change can be applied to cmsis_gcc.h.


Is `#if (__ARM_ARCH >= 8) ` a better way?

Also. Since it looks like we (IAR) haven't thought about v8.1M in CMSIS, is it possible that we are missing more features?

**Comment by JonatanAntoni** [comment]
@RobinKastberg, this is kind of compiler specific and depends on what defines you have available. And yes, defines like `__ARM_ARCH_8_1M_MAIN__` do not scale well and if possible using `__ARM_ARCH` might be a good one.

**Comment by holden-zenith** [comment]
@JonatanAntoni Oh yeah I will try to finish today, I was away last weeks.

**Review by JonatanAntoni — APPROVED** [review]

**Pull request merged**
